# A reusable workflow to plan a Terraform build
name: Plan a tf build
on:
  workflow_call:
    inputs:
      # Which stack/folder to deploy
      stack:
        required: true
        type: string
      action:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      OVH_APPLICATION_KEY:
        required: true
      OVH_APPLICATION_SECRET:
        required: true
      OVH_CONSUMER_KEY:
        required: true
      DOMENESHOP_TOKEN:
        required: false
      DOMENESHOP_SECRET:
        required: false
      

jobs:
  tofu:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    defaults:
      run:
        working-directory: ${{ inputs.stack }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: OpenTofu Init
        run: tofu init
      - name: OpenTofu ${{ inputs.action }}
        run: tofu ${{ inputs.action }} ${{ inputs.action=='fmt' && '-check' || '' }} ${{ inputs.action=='plan' && format('-out=tfplan-{0}.binary', inputs.stack) || '' }}
      - name: Upload tfplan as artifact
        uses: actions/upload-artifact@v5
        if: ${{ inputs.action == 'plan' }}
        with:
          name: tfplan-${{ inputs.stack }}
          # actions/upload-artifact does not inherit the job run.working-directory, so we must prefix with the stack folder
          path: ${{ inputs.stack }}/tfplan-${{ inputs.stack }}.binary
      - name: Generate human-readable plan
        if: ${{ inputs.action == 'plan' }}
        run: tofu show -no-color tfplan-${{ inputs.stack }}.binary > tfplan-${{ inputs.stack }}.txt
      - name: Upload plan text as artifact
        if: ${{ inputs.action == 'plan' }}
        uses: actions/upload-artifact@v5
        with:
          name: tfplan-${{ inputs.stack }}-text
          # Prefix path with stack folder for same reason as above
          path: ${{ inputs.stack }}/tfplan-${{ inputs.stack }}.txt
    env:
      OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
      OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
      OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOMENESHOP_TOKEN: ${{ secrets.DOMENESHOP_TOKEN }}
      DOMENESHOP_SECRET: ${{ secrets.DOMENESHOP_SECRET }}